### ISSUE TITLE
Make classes PSR-4 compliant

### ISSUE THREAD

**Issue by Cambis** [silverstripe/silverstripe-segment-field#103]
### Description

The classes in this module are not PSR-4 compliant, this can lead to some issues with autoloading.

Specifically...
- composer.json `autoload` entry points to the `code/` directory when it should point to `src/`.
- classes in `tests/SegmentFieldModifier` do not include `SegmentFieldModifier` in their namespace. 

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/silverstripe/silverstripe-segment-field/pull/104

**Comment by GuySartorelli** [comment]
Silverstripe CMS has its own autoloading that allows for non-PSR-4 compliant classes - are you experiencing any actual loss of functionality, or any error messages in the logs, etc as a result of the lack of compliance?

**Comment by Cambis** [comment]
Hi @GuySartorelli the specific issue I've found is when using the `@runInSeparateProcess` annotation in a unit test, it throws something like this for me

```
Class SilverStripe\Forms\SegmentFieldModifier\AbstractSegmentFieldModifier was not found in SilverStripe\Forms\Tests\SegmentFieldTest
```

**Comment by GuySartorelli** [comment]
PR merged.
