### ISSUE TITLE
Move Scrutinizer to silverstripe organisation

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-segment-field#18]
@assertchris would you mind moving the Scrutinizer configuration to silverstripe for this module please?

You could add me to it with admin access and I could do it too.

https://scrutinizer-ci.com/g/silverstripe-labs/silverstripe-segment-field/

Cheers!

**Comment by assertchris** [comment]
Sure! I've pointed it to this repo and added you as admin, so you should be able to make any further changes you like! :)

**Comment by robbieaverill** [comment]
The man! Thanks :-)
