### ISSUE TITLE
Non-english tags/categories can create empty (NULL) URLSegments

### ISSUE THREAD

**Issue by alialamshahi** [silverstripe/silverstripe-segment-field#5]
Hello,
In Silverstripe-blog, when you create a non-English tag or category you get a null URLSegment. 
Create a tag with the title `شخصی و افراد` and save.
Click the tag in the front-end - notice there is no URLSegment and the link leads to 404.

**Comment by robbieaverill** [comment]
Hey @alialamshahi, I think this issue was fixed in the blog module with https://github.com/silverstripe/silverstripe-blog/pull/466. Please feel free to reopen this issue if you're still experiencing the problem!
